### ISSUE TITLE
how to add borer radius into caroselImageStyle ?

### ISSUE THREAD

**Issue by kasimkazmi** [Mudassirraza912/react-native-image-slider-banner#2]
how can I add border-radius to the image caroselImageStyle prop only take height width?

**Comment by Mudassirraza912** [comment]
@kasimkazmi @kasimkazmi try this `caroselImageContainerStyle={{borderRadius: 50,  overflow: 'hidden'}}
![Screen Shot 2022-01-13 at 5 12 04 PM](https://user-images.githubusercontent.com/39431881/149328155-e51a1979-6dee-4b2e-b825-0f191d7ee0e6.png)
`
